# Generated by Django 5.0.2 on 2024-02-14 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(
                    choices=[('QURAN_AYAH', 'Quran Ayah'), ('HADITH', 'Hadith'), ('PICTURE', 'Picture'),
                             ('DHIKR', 'Dhikr'), ('YOUTUBE', 'YouTube')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content',
                 models.TextField(verbose_name='Content of the card (e.g., Ayah text, Hadith text, Dhikr title)')),
                ('additional_info', models.TextField(blank=True, null=True,
                                                     verbose_name='Additional information related to the card (e.g., Surah title, Name of Narrator)')),
                ('arabic_text', models.TextField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, null=True,
                                                verbose_name='URL of the content (e.g., YouTube URL, Picture URL)')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('repeat', models.CharField(
                    choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'),
                             ('custom', 'Custom')], default='daily', max_length=10)),
                ('repeat_days', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('play_in_app', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='UserCardInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type',
                 models.CharField(choices=[('like', 'Like'), ('hide', 'Hide'), ('dhikr', 'Dhikr')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sajda.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Взаимодействие пользователя с карточкой',
                'verbose_name_plural': 'Взаимодействия пользователей с карточками',
            },
        ),
    ]
